### ISSUE TITLE
Hello, I would like to ask how to use this plugin?

### ISSUE THREAD

**Issue by chencu5958** [GloMC/LoadBalancer#1]
I tried to follow the methods in the readme document, but I'm not sure how to use this plugin or how to use it on the velocity side?

**Comment by alaajel** [comment]
Hello sorry for very late response, this project is just an API to help you with load balancing, you will need to code rest of the stuff yourself.

**Comment by chencu5958** [comment]
> Hello sorry for very late response, this project is just an API to help you with load balancing, you will need to code rest of the stuff yourself.

Okay, thank you for your reply. Now I can figure out what it's used for
